### ISSUE TITLE
Not hip enough. Rewrite in swift? It is webscale.

### ISSUE THREAD

**Issue by ebolyen** [ElDeveloper/keystats#9]
Github recently wrote a [tutorial](https://github.com/blog/1946-create-pull-requests-with-github-for-mac) about how to do this: ![](https://cloud.githubusercontent.com/assets/13760/5697198/35b8c866-999f-11e4-91c1-7af538f2ced5.gif)

**Comment by antgonza** [comment]
:+1:

**Comment by ElDeveloper** [comment]
@ebolyen, while that makes sense on the long term, I don't think this is something we'll be able to support any time soon. Specifically CorePlot has [a few known](https://github.com/core-plot/core-plot/issues/96) issues with Swift. For now I'll tag this as `won't fix`.

Note that if someone were to port the codebase over to Swift I would support that PR and make sure we could get it into a useable state.
